variables:
  ARTIFACT_ID: "gitlab-ci-templates"
  SERVICE_PORT: "0"

include:
  - https://raw.githubusercontent.com/michael-wirth/gitlab-ci-templates/master/.maven.yml
  - https://raw.githubusercontent.com/michael-wirth/gitlab-ci-templates/master/.semantic-release.yml
  - https://raw.githubusercontent.com/michael-wirth/gitlab-ci-templates/master/.deploy.yml
